# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: curl -o Fusion360.pkg https://dl-test.appstreaming.autodesk.com/dev/installers/Autodesk%20Fusion%20360%20Admin%20Install.pkg
  displayName: 'Download Fusion 360

- script: pwd
  displayName: 'pwd'

- script: ls
  displayName: 'List directory contents'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
